pipeline:
  name: TestAmy2
  identifier: TestAmy2
  projectIdentifier: AmyTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: TestStage
        identifier: TestStage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          whoami
                          export PATH="$PATH:/opt/liquibase/liquibase"
                          echo $PATH
                          pwd
                          git --version
                          /opt/liquibase/liquibase/liquibase -v
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
