pipeline:
  name: TestAmy2
  identifier: TestAmy2
  projectIdentifier: AmyTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: TestStage
        identifier: TestStage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          whoami
                          export PATH="$PATH:/opt/liquibase/liquibase"
                          echo $PATH
                          git --version
                          VERSION="$(curl  -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/liquibase/liquibase/releases/latest | grep -o "v.*" | grep -v "\"\," | grep "core.*jar" | sed s/"v"//g | sed s/"\/.*"//g)"
                          echo $VERSION
                          #curl -L https://github.com/liquibase/liquibase/releases/download/v${VERSION}/liquibase-${VERSION}.zip --output liquibase-${VERSION}.zip
                          #unzip -o -d liquibase-${VERSION} liquibase-${VERSION}.zip
                          unzip --version
                          tar --help
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
